INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-AN', 'Andaman and Nicobar');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Andaman and Nicobar');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-AP', 'Andhra Pradesh');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Andhra Pradesh');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-AR', 'Arunachal Pradesh');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Arunachal Pradesh');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-AS', 'Assam');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Assam');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-BR', 'Bihar');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Bihar');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-CH', 'Chandigarh');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Chandigarh');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-CG', 'Chhattisgarh');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Chhattisgarh');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-DN', 'Dadra and Nagar Haveli');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Dadra and Nagar Haveli');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-DD', 'Daman and Diu');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Daman and Diu');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-DL', 'Delhi');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Delhi');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-GA', 'Goa');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Goa');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-GJ', 'Gujarat');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Gujarat');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-HR', 'Haryana');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Haryana');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-HP', 'Himachal Pradesh');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Himachal Pradesh');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-JK', 'Jammu and Kashmir');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Jammu and Kashmir');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-JH', 'Jharkhand');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Jharkhand');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-KA', 'Karnataka');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Karnataka');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-KL', 'Kerala');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Kerala');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-LD', 'Lakshadweep');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Lakshadweep');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-MP', 'Madhya Pradesh');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Madhya Pradesh');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-MH', 'Maharashtra');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Maharashtra');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-MN', 'Manipur');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Manipur');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-ML', 'Meghalaya');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Meghalaya');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-MZ', 'Mizoram');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Mizoram');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-NL', 'Nagaland');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Nagaland');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-OR', 'Orissa');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Orissa');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-PY', 'Puducherry');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Puducherry');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-PB', 'Punjab');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Punjab');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-RJ', 'Rajasthan');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Rajasthan');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-SK', 'Sikkim');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Sikkim');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-TN', 'Tamil Nadu');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Tamil Nadu');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-TR', 'Tripura');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Tripura');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-UK', 'Uttarakhand');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Uttarakhand');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-UP', 'Uttar Pradesh');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'Uttar Pradesh');
INSERT INTO `directory_country_region` (`country_id`, `code`, `default_name`) VALUES ('IN', 'IN-WB', 'West Bengal');
INSERT INTO `directory_country_region_name` (`locale`, `region_id`, `name`) VALUES ('en_US', LAST_INSERT_ID(), 'West Bengal');
