<div class="col-set order-info-box">
    <div class="col">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('File Uploaded') ?></h2>
            </div>
            <div class="box-content">
                
                	<table width='100%' cellspacing="0" class="form-list">
		            <?php 
		            	$_order = $this->getOrder();
		            	$files = Mage::getModel('file/order')->getFiles($_order);
		            	foreach($files as $file){ 
		            ?>
		            <tr>
		                <td style="width:20%" class="label"><strong><?php echo Mage::helper('file')->__($file['type']) ?></strong></td>
		                <td align="right" class="value"><a target="_blank" href='<?php $url =  $this->getBaseUrl().'media/uploads'.$file['filename']; echo str_replace('index.php/', '', $url); ?>'><?php echo $file['filename'];?></a></td>
		            </tr>
		            <?php } ?>
		            </table>
                
            </div>
        </div>
    </div>
</div>